export const paypalEvents = {
  APPROVED: "CHECKOUT.ORDER.APPROVED",
  COMPLETED: "PAYMENT.CAPTURE.COMPLETED",
  CANCELED: "BILLING.SUBSCRIPTION.CANCELLED",
  REFUNDED: "PAYMENT.CAPTURE.REFUNDED",
  DECLINED: "PAYMENT.CAPTURE.DECLINED",
  DENIED: "PAYMENT.CAPTURE.DENIED",
};
