version: "3.8"

networks:
  over-node:
    driver: bridge

volumes:
  mongo-data:

services:
  web:
    build:
      context: .
    image: flexipay:1.0.1
    env_file:
      - .env.compose
    ports:
      - "5000:5000"
    networks:
      - over-node

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - over-node
    volumes:
      - mongo-data:/data/db
